### ISSUE TITLE
Unable to sync to the branch

### ISSUE THREAD

**Issue by lucianoh** [cop1000/late-start-algorithm-challenges#19]
Whenever I try to sync my changes I get this error. I'd appreciate any help.
![image](https://cloud.githubusercontent.com/assets/22595449/20529438/1f895980-b09e-11e6-8462-2dcce43df82e.png)

**Comment by hectorsector** [comment]
Hi @lucianoh I don't see a commit in your history, did you commit your changes yet? If so, you can sync afterward. Or are you trying to do something else? If you can't figure this out and just want to submit it please just email me your code.
