### ISSUE TITLE
Thought I had finished?

### ISSUE THREAD

**Issue by StephanNears** [cop1000/late-start-algorithm-challenges#20]
For some reason or another the other 2 parts I put down didn't go through? Is it too late?

**Comment by hectorsector** [comment]
It's not too late, @StephanNears -- I saw your name signed up but I didn't see any actual commits attached to your name. Did you sync? Feel free to let me know how you decide to go forward.

**Comment by StephanNears** [comment]
I thought I synced up but it didn't seem to go through, I took the assignments and made a copy in my documents. Am I able to sync them up still? 

    On Thursday, December 1, 2016 8:34 PM, Hector Alfaro <notifications@github.com> wrote:
 

 It's not too late, @StephanNears -- I saw your name signed up but I didn't see any actual commits attached to your name. Did you sync? Feel free to let me know how you decide to go forward.—

**Comment by hectorsector** [comment]
?Yes, let me know what happens. If it doesn't work just email me your code.

-Prof. Alfaro

________________________________

**Comment by StephanNears** [comment]
I tried to commit the changes , but it didnt seem to work. I'm sending the files. 

    On Thursday, December 1, 2016 9:12 PM, Hector Alfaro <notifications@github.com> wrote:
 

 ?Yes, let me know what happens. If it doesn't work just email me your code.

-Prof. Alfaro

________________________________

**Comment by hectorsector** [comment]
Alright I'm waiting for them.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Fri, Dec 2, 2016 at 5:35 PM -0500, "StephanNears" <notifications@github.com<mailto:notifications@github.com>> wrote:

I tried to commit the changes , but it didnt seem to work. I'm sending the files.

On Thursday, December 1, 2016 9:12 PM, Hector Alfaro <notifications@github.com> wrote:


?Yes, let me know what happens. If it doesn't work just email me your code.

-Prof. Alfaro

________________________________
